version: "3.9"

services:
  glusterfs-node1:
    build: ./media-domain/
    container_name: glusterfs-node1
    hostname: glusterfs-node1
    volumes:
      - glusterfs-data1:/data
    networks:
      glusterfs-net:
        ipv4_address: 192.168.1.11
    privileged: true
    ports:
      - "8081:80"
    command: >
      /bin/sh -c "
      ./entrypoint.sh glusterfs-node2 glusterfs-node3 &&

      gluster volume create gv0 replica 3 transport tcp glusterfs-node1:/data/brick glusterfs-node2:/data/brick glusterfs-node3:/data/brick force &&
      gluster volume start gv0 &&
      gluster volume info &&

      ./setup.sh &&
      tail -f /dev/null"

  glusterfs-node2:
    build: ./media-domain/
    container_name: glusterfs-node2
    hostname: glusterfs-node2
    volumes:
      - glusterfs-data2:/data
    networks:
      glusterfs-net:
        ipv4_address: 192.168.1.12
    privileged: true
    ports:
      - "8082:80"
    command: >
      /bin/sh -c "
      ./entrypoint.sh glusterfs-node1 &&
      ./setup.sh &&
      tail -f /dev/null"

  glusterfs-node3:
    build: ./media-domain/
    container_name: glusterfs-node3
    hostname: glusterfs-node3
    volumes:
      - glusterfs-data3:/data
    networks:
      glusterfs-net:
        ipv4_address: 192.168.1.13
    privileged: true
    ports:
      - "8083:80"
    command: >
      /bin/sh -c "
      ./entrypoint.sh glusterfs-node1 && 
      ./setup.sh &&
      tail -f /dev/null"

volumes:
  glusterfs-data1:
  glusterfs-data2:
  glusterfs-data3:

networks:
  glusterfs-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
