version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  page_retrieval_service:
    build:
      context: ./page_retrieval_service
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
    networks:
      - backend

  page_adding_service:
    build:
      context: ./page_adding_service
    ports:
      - "8002:8002"
    depends_on:
      - page_retrieval_service
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
