version: "3.9"

services:
  page_retrieval_service_db:
    image: postgres:14
    environment:
      POSTGRES_USER:     myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB:       mydb
      PGDATA:            /var/lib/postgresql/data/pgdata
    healthcheck:
      test:       ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval:   5s
      timeout:    5s
      retries:    5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      backend: {}
      shared-net: {}

  page_retrieval_service:
    build:
      context: .
    expose:
      - "8001"
    environment:
      DB_HOST:       page_retrieval_service_db
      DB_PORT:       5432
      DB_NAME:       mydb
      DB_USER:       myuser
      DB_PASSWORD:   mypassword
      CONSUL_HOST:   192.168.56.2
      CONSUL_PORT:   8500
    networks:
      backend: {}
      shared-net: {}

volumes:
  postgres_data:

networks:
  backend: {}
  shared-net: {}
