version: "3.9"

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    environment:
      SECRET_KEY: "your_very_secret_key"
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
      INSTANCE_ID: "auth-0"
      INSTANCE_HOST: "auth-service"
      INSTANCE_PORT: 9100
    ports:
      - "9100:9100"
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres-auth
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:

